### ISSUE TITLE
Provide MKDocs documentation

### ISSUE THREAD

**Issue by jensschuppe** [systopia/de.systopia.fastactivity#10]
Easy task: Add mkdocs.yml and a link to the readme.

PR coming soon ...

**Comment by bjendres** [comment]
Somebody should review the documentation. @mattwire, would you have a look?

**Comment by mattwire** [comment]
@systopia I've reviewed the documentation and confirm it is correct.

**Comment by bjendres** [comment]
@mattwire awesome, thanks
