### ISSUE TITLE
Error due to removed Core method

### ISSUE THREAD

**Issue by jensschuppe** [systopia/de.systopia.fastactivity#45]
#34 introduced some code that calls `CRM_Core_Form_Date::buildDateRange()` which got removed with https://github.com/civicrm/civicrm-core/commit/83966bf9111f2b7a5f33ec7716eca0c412d027dd in CiviCRM 5.61.0.

@pfigel you were the author of #34, would you be able to look into that?

**Comment by bjendres** [comment]
For the time being, I'll add the required code to the ``legacycode`` extension.

**Comment by jensschuppe** [comment]
We should instead copy the removed method into this extension and not rely on the `legacycode` extension as a dependency.
