### ISSUE TITLE
Not compatible with 4.7+

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.fastactivity#6]
Unfortunately, the extension is *not* compatible with CiviCRM ``4.7+``, since the ``CRM_Core_BAO_Setting::inCache()`` call used [HERE](https://github.com/systopia/de.systopia.fastactivity/blob/1.0.beta2/CRM/Fastactivity/Page/AJAX.php#L75-L83) has not been around since ``4.7.0``.

@mattwire: should I release ``1.0`` as ``4.6`` only?

**Comment by mattwire** [comment]
Ok. Looks like I just dropped the cache function on my fork: https://github.com/mattwire/de.systopia.fastactivity/blob/master/CRM/Fastactivity/Page/AJAX.php#L86

@systopia If you are ready for a release, just release it now as 1.0 for 4.6 (or remove the cache and release for 4.6/4.7+). Then we can work on merging my changes.

**Comment by bjendres** [comment]
>  just release it now as 1.0 for 4.6

Will do that, thanks @mattwire

**Comment by bjendres** [comment]
@mattwire I merged your fork into ``master`` (destined to be ``1.1``). Let the testing begin!

**Comment by bjendres** [comment]
@mattwire I merged your PRs to ``master``. Could you confirm that that works as expected with your CiviCRM version (presumably 5.6+)?

**Comment by mattwire** [comment]
@systopia Yes it is working on latest release (5.8.2).  We can close this issue
